<?php

return [
    'host' => 'MYSQL_HOST_FROM_INFINITYFREE_PANEL',
    'user' => 'MYSQL_USERNAME_FROM_INFINITYFREE_PANEL',
    'password' => 'MYSQL_PASSWORD_FROM_INFINITYFREE_PANEL',
    'database' => 'MYSQL_DATABASE_NAME_FROM_INFINITYFREE_PANEL',
];